name: Generate Slides and Publish to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert Markdown into HTML and PDF
        uses: KoharaKazuya/marp-cli-action@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: slides
          path: slides.pdf
