name: Generate Slides and Publish to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: '20.11.1'
      - name: Install dependencies
        run: npm ci
      - name: Set envivonment var for chrome sandbox
        run: echo "CHROME_NO_SANDBOX=1" >> $GITHUB_ENV
      - name: Test chrome environment var
        run: echo $CHROME_NO_SANDBOX
      - name: Set envivonment for puppeteer timeout
        run: echo "PUPPETEER_TIMEOUT=0" >> $GITHUB_ENV
      - name: Test puppet environment var
        run: echo $PUPPETEER_TIMEOUT
      - name: Build Marp slide deck
        run: CHROME_PATH=$(npx -y @puppeteer/browsers@latest install chrome@stable --path $(realpath ./tmp) | awk '{print $2}') npm run build:all
      - uses: actions/upload-artifact@v4
        with:
          name: slides
          path: |
            dist/*.pdf
      - name: Update username config.
        run: git config --local user.name "github-actions[bot]"
      - name: Update the user email config.
        run: git config --local user.email "github-actions[bot]@users.noreply.github.com"
      - name: Stage changed files.
        run: |
          mv dist/slides.html dist/index.html
          git add -f dist/index.html dist/slides.pdf
      - name: Commit changed files.
        run: git commit -m "Auto updating presentation files."
      - name: Push code to main
        run: git push origin main
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4